### ISSUE TITLE
Failed to load data

### ISSUE THREAD

**Issue by nschah** [thenikhilk/sharepoint-instagram-feed#4]
**Describe the bug**
Error occurs after adding the webpart to the page. Changing username to other public profiles and own doesnt resolve it

> An error occurred - Failed to load data, please check WebPart settings or try again later.

<img width="904" alt="Bildschirmfoto 2019-11-07 um 11 28 10" src="https://user-images.githubusercontent.com/17612292/68383788-9a8d7b00-0156-11ea-8b85-015a7f81a85a.png">

Console:
<img width="550" alt="Bildschirmfoto 2019-11-07 um 12 06 15" src="https://user-images.githubusercontent.com/17612292/68384052-0ec81e80-0157-11ea-81e7-ffb5c1691620.png">

**Comment by thenikhilk** [comment]
could you also give network details?
any failed requests from cdn?

![image](https://user-images.githubusercontent.com/5794800/68384731-47c7b980-017e-11ea-927d-221680c9d1d4.png)

**Comment by thenikhilk** [comment]
if the issues are related to the CDN like 404 you could just host a CDN within SharePoint yourself and not rely on any external dependency:
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/hosting-webpart-from-office-365-cdn

**Comment by nschah** [comment]
Network
<img width="1236" alt="Bildschirmfoto 2019-11-07 um 12 18 57" src="https://user-images.githubusercontent.com/17612292/68384917-fc4ee480-0158-11ea-8cbb-00591f24a8ba.png">

**Comment by thijsvgils** [comment]
As stated in the other issue, same errors for me. Also no 404 errors in the network pane!

**Comment by thenikhilk** [comment]
Just to confirm this is a SharePoint online page?

**Comment by thijsvgils** [comment]
> Just to confirm this is a SharePoint online page?

yes that's correct

**Comment by nschah** [comment]
Yes a modern page

**Comment by thenikhilk** [comment]
Just uninstall the previous web part and install this version in the ZIP file, I've removed all references to the CDN it's all native now.

**Just upload this Web Part in the App Catalog, and deploy**
![image](https://user-images.githubusercontent.com/5794800/68387063-71cfaa80-0183-11ea-8b93-1b22ca6c447a.png)

**Go to the site where you want to use and add it as an App**
![image](https://user-images.githubusercontent.com/5794800/68387241-e1de3080-0183-11ea-9fa6-688571ab748b.png)
![image](https://user-images.githubusercontent.com/5794800/68387246-e571b780-0183-11ea-8d01-9b01059b7f4a.png)

Add the web part on the web page
![image](https://user-images.githubusercontent.com/5794800/68387305-089c6700-0184-11ea-96e8-168c0407c195.png)


[thenikhilk-sp-ig-feed.zip](https://github.com/thenikhilk/sharepoint-instagram-feed/files/3819428/thenikhilk-sp-ig-feed.zip)


Let me know if this works

**Comment by thijsvgils** [comment]
tried it, but same error:

![image](https://user-images.githubusercontent.com/34765064/68388184-556e4680-0160-11ea-8432-0a4d960b282b.png)

**Comment by thenikhilk** [comment]
I'll look into this further, maybe browser support for fetch,

Till the time I'll ask for the browser you used and may be you could try making a build at your end
https://github.com/thenikhilk/sharepoint-instagram-feed/blob/master/documentation/developer-guide.md

**Comment by thenikhilk** [comment]
@nschah @thijsvgils Fixed. Changed the logic and dependencies, included extra error handling, removed CDN dependencies, and here you go:
![image](https://user-images.githubusercontent.com/5794800/68411678-e836d180-01b0-11ea-9147-fd48aa8f07fe.png)

Updated package: [thenikhilk-sp-ig-feed.zip](https://github.com/thenikhilk/sharepoint-instagram-feed/files/3820887/thenikhilk-sp-ig-feed.zip)

Let me know if it works for you now, then I'll merge to master and create a new release
changes in #5

**Comment by thenikhilk** [comment]
Fixed issue please refer to the release package for web part in v1.0.2 https://github.com/thenikhilk/sharepoint-instagram-feed/releases

@nschah @thijsvgils I hope your issue was solved I've tested them out on multiple tenants, they seem to be working now
![image](https://user-images.githubusercontent.com/5794800/68469370-0a2b6500-0240-11ea-9a1f-01826cd64f04.png)

**Comment by thijsvgils** [comment]
Hi @thenikhilk, No errors on the page this time, but still not showing insta posts. This is the error i'm getting in my console:
![image](https://user-images.githubusercontent.com/34765064/68469869-4e583e80-021b-11ea-8ffc-ad871d3b7cdc.png)

This is what i see on the page:
![image](https://user-images.githubusercontent.com/34765064/68469910-5c0dc400-021b-11ea-84ea-87c018739af9.png)

**Comment by thenikhilk** [comment]
any way we could connect over chat or screen share?

**Comment by thijsvgils** [comment]
Sure, shall i send you a MS Teams call to your email address? I can meet in 1,5 hour, would that be ok?

**Comment by thenikhilk** [comment]
ok, or just mail me the invite link. I'll join there

**Comment by manFER83** [comment]
I´ve been having the same problem.

**Comment by nschah** [comment]
@thenikhilk @thijsvgils 
any News to the issue? On my page its working sometimes, but mostly not.
<img width="552" alt="Bildschirmfoto 2019-11-11 um 12 03 45" src="https://user-images.githubusercontent.com/17612292/68582584-6201e000-047b-11ea-9b3f-09ac625ac51a.png">

**Comment by thijsvgils** [comment]
@nschah @thenikhilk Same here, sometimes it works sometimes it doesnt. @thenikhilk is still looking into it.

**Comment by thenikhilk** [comment]
I have a fix for this, I'll be publishing it over the weekend

**Comment by TAKSoftware** [comment]
Hi Nikhil, Please can you fix the issue and update the repository, as i am not able to fix it.
It would be great helpful, if you do so.

**Comment by patrickb2012** [comment]
@thenikhilk Any update?

**Comment by BennyD-Savaco** [comment]
Hi, i've installed the spkkg from the repository but it still shows version 1.0.1.0, when will version 1.0.2 be available?

**Comment by thenikhilk** [comment]
Please try out this version, it should work:
[thenikhilk-sp-ig-feed.zip](https://github.com/thenikhilk/sharepoint-instagram-feed/files/3896275/thenikhilk-sp-ig-feed.zip)

The thing is even though I do acknowledge the issue exists, it has never been a repro in any of the environments I've used, but I have seen it repro in my sync up with @thijsvgils . SO it becomes hard debug it.

**Comment by BennyD-Savaco** [comment]
I've installed version 1.0.3, now the app shows 3 blank grey squares so no content from Instagram, when i inspect the webpart in chrome, it says "not-logged-in client-root"

**Comment by thenikhilk** [comment]
@BennyD-Savaco could you provide me some additional debugging info by 

- giving my a screenshot of your browser console after pressing F12 and reloading the page
- Provide sample network responses for any failing requests in a text file
![image](https://user-images.githubusercontent.com/5794800/69717914-00a46700-1133-11ea-88fe-feff6352e85c.png)

**Comment by MattVandepitte** [comment]
@thenikhilk FYI I'm a colleague of BennyD-Savaco
The problem were having is that the webparts keeps sending requests. It looks like we are in an endless loop of requests:
![image](https://user-images.githubusercontent.com/45657988/69722890-7e0eae00-1118-11ea-82f2-ec112321c4f8.png)
We are always getting a response(statuscode 200) and the webpage is returned:
![image](https://user-images.githubusercontent.com/45657988/69723006-c4640d00-1118-11ea-80e0-a079b12c7b12.png)
But we keep seeing the tree grey squares.

**Comment by thenikhilk** [comment]
Your analysis is correct, it is doing so to try out different proxy servers if one doesn't work. But if all fail for a long duration there is really nothing else i can do other that use access tokens. These proxies are what empower this web part
